In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

In [3]:
df.head()

    A   B   C   D
0  35  79  97  17
1  15  49  10  10
2  30  56   3  79
3  27   6  31  18
4  50  91   7  26

In [4]:
df['Count'] = df[[ 'A','B','C']].ge(df['D'],axis=0).sum(axis=1)
df

     A   B   C   D  Count
0   35  79  97  17      3
1   15  49  10  10      3
2   30  56   3  79      0
3   27   6  31  18      2
4   50  91   7  26      2
5   70  85  26  80      1
6   94  93   0  27      2
7   84   2  32  68      1
8    8  87  70  74      1
9    9  43  36   1      3
10  70  22   0  56      1
11  42  90  61  90      1
12  13  99  99  40      2
13  39  46  68  63      1
14   3  79   5   7      1
15  31  73  40  19      3
16  95  13  40  92      1
17  84  99  16  16      3
18  88  11  74  55      2
19  49  77  35  88      0
20  48  90  81  61      2
21  97  93  44  62      2
22  84  23  41  49      1
23  89  59  94  74      2
24  22  46  15  30      1
25   0  87   7  58      1
26  23  48   9  84      0
27  22  48   5  28      1
28  27  10  48  49      0
29  10  67  67  41      2
..  ..  ..  ..  ..    ...
70  72  46  32  66      1
71  61  34  53  61      1
72  22  51  87  24      2
73   6  47  21  58      0
74   8  61  17  94      0
75  76  17  34  71      1
76  82  66  97   2      3
77  57  42  99  12      3
78  54  62   4  99      0
79  51   0  75  68      1
80  57  44   7  50      1
81  22  31  71  47      1
82  79  46  95  24      3
83  56  40  16  39      2
84  44  77  73  51      2
85  66  69  21  96      0
86  28  71  94  86      1
87  84  19  91  58      2
88  45  15  10  72      0
89  29  42  50  91      0
90   6  45  68  30      2
91  61  25  69  67      1
92  37  94  89  62      2
93   3  72  51  65      1
94  61  13  43  84      0
95  30  79  82  34      2
96  98  86  20  66      2
97  11  70  39  72      0
98  64   1  28  91      0
99   5  54  98  96      1

[100 rows x 5 columns]